site:
  name: mobicheckin-website

  locales: [en, fr]

  seo_title: mobicheckin-website
  meta_keywords: "some meta keywords"
  meta_description: "some meta description"

  pages:
    - "index": # page path (the template can edited here app/views/pages/index.liquid)
        title: "Home page"
        published: true
    - "features" :
        title: "Features"
        published: true
    - features/content_type_template:
        templatized: true
        published: true
        model: features
        title: Template of a feature
    - "events" :
        title: "Events"
        published: true
    - "pricing" :
        title: "Pricing"
        published: true
    - "devis" :
        title: "Devis"
        published: true
    - "404":
        title: "Page not found"
        published: true